module.exports={
    env:{
        "BASE_URL":"http://localhost:3000",
        "MONGODB_URL":"mongodb+srv://ayhan:ayhan@cluster0.1ioo2.mongodb.net/nextjs_ecommerce?retryWrites=true&w=majority",
        "ACCESS_TOKEN_SECRET":"'T$ASv(LWh^mKwH}#MhK=T^5Vd*27eQ;)t]JhBMQ/TyN;[{-+",
        "REFRESH_TOKEN_SECRET":"F)^&X/-=Q;mX+Qng.L$!RGE@rN$un]8pmr4Sv)bkF&H2arJuyHwR}[&xH_fKN~?s8].ne9_8VHLzNY",
        "PAYPAL_CLIENT_ID":"AWrktSXIXgXUyChVDtk3JPSLu209b2mnl7gw5PP7mH5cqirK8IVJJA0-Vu7XHxyq2WMsJoG3xA5Cvd0K"
   }
}